#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


# Restrict push to `main` branch
if [ $(git rev-parse --abbrev-ref HEAD) != "main" ]; then
  echo "Pushing to non-main branch is not allowed"
  exit 1
fi

pnpm lint
pnpm build
